### ISSUE TITLE
Error when using old swap cookbook 0.3.0

### ISSUE THREAD

**Issue by daveallen** [zuazo/swap_tuning-cookbook#4]
I am applying your cookbook to Ubuntu 16.04 and the only way I can get it to work is by removing the lock on the swap cookbook 0.3.0 and letting it use swap 2.1.0.

Can you remove the version lock please?

**Comment by zuazo** [comment]
Hi @daveallen,

Thanks for the report. Could you open a PR with the fix?

**Comment by daveallen** [comment]
Just saw this.  Pull request added.

**Comment by zuazo** [comment]
Closing it in favor of #5.
